version: '3.3'

services:

  bot:
    build:
      context: ./server
    command: sh -c "python -m bot"

  back-end:
    user: "root"
    build:
      context: ./server
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput  && python manage.py makemigrations && python manage.py migrate &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000 --access-logfile -"
    ports:
      - "80:8000"