# Generated by Django 5.0.2 on 2024-02-27 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='access_answer',
        ),
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='quiz_user', to='quiz.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='result_quiz',
            field=models.ManyToManyField(blank=True, null=True, related_name='result_quiz_user', to='quiz.quizresult'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
    ]
